# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f33616baf5447d20111776a7375f054ef52f11b91c71c4867970d1301d388e98ee92796c298fee8cc098e875036a6fe85e9b8ddb35604305d70b99930354077a

test:
  secret_key_base: 00d0316c0c126adbfb45aec99d69020b8079afeca0661aad912e8f263b1a67f1568a9ce4952ea8fc60fa048090d96553380e46bcbb0b3742e0b94321b6ae87c4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
